schema:
  env: minikube

redis-cluster:
  global:
    defaultStorageClass: "nfs-client"
    storageClass: "nfs-client"
#    security:
#      allowInsecureImages: false
#    redis:
#      password: ""
#    compatibility:
#      openshift:
#        adaptSecurityContext: disabled
#
#  commonAnnotations: {}
#  commonLabels: {}
#  diagnosticMode:
#    enabled: false
#
  image:
    registry: docker.io
    repository: bitnamilegacy/redis-cluster
    pullPolicy: IfNotPresent
#
#  networkPolicy:
#    enabled: true
#    allowExternal: true
#    allowExternalEgress: true
#    extraIngress: []
#    extraEgress: []
#
#  serviceAccount:
#    create: true
#    annotations: {}
#    automountServiceAccountToken: false
#
#  rbac:
#    create: false
#    role:
#      rules: []
#      ## rules:
#      ##  - apiGroups:
#      ##    - extensions
#      ##    resources:
#      ##      - podsecuritypolicies
#      ##    verbs:
#      ##      - use
#      ##    resourceNames:
#      ##      - gce.unprivileged
#
#  podSecurityContext:
#    enabled: true
#    fsGroupChangePolicy: Always
#    supplementalGroups: []
#    fsGroup: 1001
#    sysctls: []
#
#  pdb:
#    create: true
#    minAvailable: ""
#    maxUnavailable: ""
#
#  ## Containers Security Context
#  containerSecurityContext:
#    enabled: true
#    seLinuxOptions: {}
#    runAsUser: 1001
#    runAsGroup: 1001
#    runAsNonRoot: true
#    privileged: false
#    readOnlyRootFilesystem: true
#    allowPrivilegeEscalation: false
#    capabilities:
#      drop: ["ALL"]
#    seccompProfile:
#      type: "RuntimeDefault"
#
#  ## @param usePassword Use password authentication
#  usePassword: false
#  existingSecret: "redis-password"
#  existingSecretPasswordKey: "password"
#  usePasswordFiles: false
#
#  tls:
#    enabled: true
#    ## @param tls.authClients Require clients to authenticate or not
#    ##
#    authClients: false
#    autoGenerated: false
#    existingSecret: "redis-tls"
#    certificatesSecret: ""
#    certFilename: "tls.crt"
#    certKeyFilename: "tls.key"
#    certCAFilename: "ca.crt"
#    dhParamsFilename: ""
#
#  service:
#    ports:
#      redis: 6379
#    annotations: {}
#    labels: {}
#    type: ClusterIP
#    loadBalancerIP: ""
#    loadBalancerClass: ""
#    loadBalancerSourceRanges: []
#    externalTrafficPolicy: Cluster
#    headless:
#      annotations: {}
#
#  persistence:
#    enabled: false
#    path: /bitnami/redis/data
#    subPath: ""
#    storageClass: "nfs-client"
#    accessModes:
#      - ReadWriteOnce
#    size: 8Gi
#
#  persistentVolumeClaimRetentionPolicy:
#    enabled: false
#    whenScaled: Retain
#    whenDeleted: Retain
#
#  ## Init containers parameters:
#  volumePermissions:
#    enabled: false
#    image:
#      registry: docker.io
#      repository: bitnamilegacy/os-shell
#      #tag: 12-debian-12-r51
#      #digest: ""
#      pullPolicy: IfNotPresent
#      pullSecrets: []
#
#    ## Containers Security Context
#    containerSecurityContext:
#      enabled: true
#      seLinuxOptions: {}
#      runAsUser: 0
#      privileged: false
#
#    ## Container resource requests and limits
#    resourcesPreset: "nano" # nano, micro, small, medium, large,xlarge,2xlarge
#    resources: {}
#
#  serviceBindings:
#    enabled: false
#
#  podSecurityPolicy:
#    create: false
#
#  redis:
#    command: []
#    args: []
#    updateStrategy:
#      type: RollingUpdate
#    automountServiceAccountToken: false
#    hostAliases: []
#    hostNetwork: false
#    ## @param redis.useAOFPersistence Whether to use AOF Persistence mode or not
#    ## It is strongly recommended to use this type when dealing with clusters
#    ## ref: https://redis.io/topics/persistence#append-only-file
#    ## ref: https://redis.io/topics/cluster-tutorial#creating-and-using-a-redis-cluster
#    ##
#    useAOFPersistence: "yes"
#    ## @param redis.containerPorts.redis Redis&reg; port
#    containerPorts:
#      redis: 6379
#      bus: 16379
#    extraVolumes:
#      - name: own-ca-bundle
#        configMap:
#          name: own-ca-bundle
#          defaultMode: 0644
#          optional: false
#          items:
#            - key: own-ca-bundle.pem
#              path: ca-certificates.crt
#      - name: redis-users-acl
#        secret:
#          secretName: redis-users-acl
#    extraVolumeMounts:
#      - mountPath: /etc/ssl/certs/
#        name: own-ca-bundle
#        readOnly: true
#      - name: redis-users-acl
#        readOnly: true
#        subPath: users.acl
#        mountPath: "/opt/bitnami/redis/etc/users.acl"
#    ## @param redis.extraEnvVars An array to add extra environment variables
#    ## For example:
#    ##  - name: BEARER_AUTH
#    ##    value: true
#    ##
#    extraEnvVars: []
#    ## @param redis.extraEnvVarsCM ConfigMap with extra environment variables
#    ##
#    extraEnvVarsCM: ""
#    ## @param redis.extraEnvVarsSecret Secret with extra environment variables
#    ##
#    extraEnvVarsSecret: ""
#    ## @param redis.podAnnotations Redis&reg; additional annotations
#    ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
#    ##
#    podAnnotations: {}
#    resourcesPreset: "nano"
#    resources: {}
#
#  ## Cluster update job settings
#  updateJob:
#    activeDeadlineSeconds: 600
#    automountServiceAccountToken: false
#    helmHook: post-upgrade
#    extraVolumes:
#      - name: own-ca-bundle
#        configMap:
#          name: own-ca-bundle
#          defaultMode: 0644
#          optional: false
#          items:
#            - key: own-ca-bundle.pem
#              path: ca-certificates.crt
#      - name: redis-users-acl
#        secret:
#          secretName: redis-users-acl
#    extraVolumeMounts:
#      - mountPath: /etc/ssl/certs/
#        name: own-ca-bundle
#        readOnly: true
#      - name: redis-users-acl
#        readOnly: true
#        subPath: users.acl
#        mountPath: "/opt/bitnami/redis/etc/users.acl"
#    resourcesPreset: "nano"
#    resources: {}
#  
#  ## Redis(R) Cluster settings
#  cluster:
#    init: false
#    ## This is total number of nodes including the replicas. Meaning there will be 3 master and 3 replica
#    ## nodes (as replica count is set to 1 by default, there will be 1 replica per master node).
#    ## Hence, nodes = numberOfMasterNodes + numberOfMasterNodes * replicas
#    ##
#    ## @param cluster.nodes The number of master nodes should always be >= 3, otherwise cluster creation will fail
#    ##
#    nodes: 6
#    ## @param cluster.replicas Number of replicas for every master in the cluster
#    ## Parameter to be passed as --cluster-replicas to the redis-cli --cluster create
#    ## 1 means that we want a replica for every master created
#    ##
#    replicas: 1
#    ## Configuration to access the Redis(R) Cluster from outside the Kubernetes cluster
#    ##
#    externalAccess:
#      ## @param cluster.externalAccess.enabled Enable access to the Redis
#      ##
#      enabled: false
#      ## @param cluster.externalAccess.hostMode Set cluster preferred endpoint type as hostname
#      ## ref: https://github.com/redis/redis/pull/9530
#      ##
#      hostMode: false
#      service:
#        ## @param cluster.externalAccess.service.disableLoadBalancerIP Disable use of `Service.spec.loadBalancerIP`
#        ##
#        disableLoadBalancerIP: false
#        ## @param cluster.externalAccess.service.loadBalancerIPAnnotaion Name of annotation to specify fixed IP for service in. Disables `Service.spec.loadBalancerIP` if not empty
#        ##
#        loadBalancerIPAnnotaion: ""
#        ## @param cluster.externalAccess.service.type Type for the services used to expose every Pod
#        ## At this moment only LoadBalancer is supported
#        ##
#        type: LoadBalancer
#        ## @param cluster.externalAccess.service.port Port for the services used to expose every Pod
#        ##
#        port: 6379
#        ## @param cluster.externalAccess.service.loadBalancerIP Array of load balancer IPs for each Redis&reg; node. Length must be the same as cluster.nodes
#        ##
#        loadBalancerIP: []
#        ## @param cluster.externalAccess.service.loadBalancerClass Load Balancer class if service type is `LoadBalancer` (optional, cloud specific)
#        ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
#        ##
#        loadBalancerClass: ""
#        ## @param cluster.externalAccess.service.loadBalancerSourceRanges Service Load Balancer sources
#        ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
#        ## e.g:
#        ## loadBalancerSourceRanges:
#        ##   - 10.10.10.0/24
#        ##
#        loadBalancerSourceRanges: []
#        ## @param cluster.externalAccess.service.annotations Annotations to add to the services used to expose every Pod of the Redis(R) Cluster
#        ##
#        annotations: {}
#    ## This section allows to update the Redis&reg; cluster nodes.
#    ##
#    update:
#      addNodes: false
#      currentNumberOfNodes: 6
#      currentNumberOfReplicas: 1
#      newExternalIPs: []
#  
#  ## Prometheus Exporter / Metrics
#  metrics:
#    enabled: false
#    image:
#      registry: docker.io
#      repository: bitnamilegacy/redis-exporter
#      #tag: 1.76.0-debian-12-r0
#      #digest: ""
#      pullPolicy: IfNotPresent
#      pullSecrets: []
#    resourcesPreset: "nano"
#    extraArgs: {}
#    ## @param metrics.extraEnvVars Array with extra environment variables to add to Redis&reg; exporter
#    ## e.g:
#    # extraEnvVars:
#    ##   - name: FOO
#    ##     value: "bar"
#    ##
#    extraEnvVars: []
#    ## @param metrics.containerPorts.http Metrics HTTP container port
#    ##
#    containerPorts:
#      http: 9121
#    ## @param metrics.podAnnotations [object] Additional annotations for Metrics exporter pod
#    ##
#    podAnnotations:
#      prometheus.io/scrape: "true"
#      prometheus.io/port: "9121"
#    podLabels: {}
#    containerSecurityContext:
#      enabled: true
#      seLinuxOptions: {}
#      runAsUser: 1001
#      runAsGroup: 1001
#      runAsNonRoot: true
#      privileged: false
#      readOnlyRootFilesystem: true
#      allowPrivilegeEscalation: false
#      capabilities:
#        drop: ["ALL"]
#      seccompProfile:
#        type: "RuntimeDefault"
#
#    serviceMonitor:
#      enabled: true
#      namespace: "monitoring"
#      labels: 
#        release: kube-prometheus-stack
#      metricRelabelings: []
#
#    prometheusRule:
#      enabled: true
#      additionalLabels:
#        release: kube-prometheus-stack
#      namespace: "monitoring"
#      rules: []
#
#    service:
#      type: ClusterIP
#      ports:
#        http: 9121
#  
#  ## Sysctl InitContainer
#  sysctlImage:
#    enabled: false
#    registry: docker.io
#    repository: bitnamilegacy/os-shell
#    #tag: 12-debian-12-r51
#    digest: ""
#    pullPolicy: IfNotPresent
#    pullSecrets: []
#    mountHostSys: false
#    containerSecurityContext:
#      enabled: true
#      seLinuxOptions: {}
#      runAsUser: 0
#      privileged: true
#    resourcesPreset: "nano"
#    resources: {}
#  
