apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-users-acl
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-vault-backend
  target:
    name: valkey-users-acl
    creationPolicy: Owner
    deletionPolicy: "Retain"
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          literal: |-
            {{`{{- range $user, $userData := . }}`}}
            user {{`{{ $user }}`}} on >{{`{{ $userData | fromJson | dig "password" "" }}`}} {{`{{ $userData | fromJson | dig "acl" "" }}`}}
            {{`{{- end }}`}}
  dataFrom:
    - extract:
        key: minikube/valkey/passwords
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore

