apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-passwords
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: external-vault-backend
    kind: ClusterSecretStore
  target:
    name: valkey-passwords
    creationPolicy: Owner
    deletionPolicy: "Retain"
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          literal: |-
            {{`{{- range $user, $userData := . }}`}}
            {{`{{ $user }}`}}: "{{`{{ $userData.password }}`}}"
            {{`{{- end }}`}}
  dataFrom:
    - extract:
        key: minikube/valkey/passwords 
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
