apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
 name: n8n-license
 namespace: n8n
spec:
 refreshInterval: 4h0m0s
 secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store

 target:
   name: n8n-license
   creationPolicy: Owner
   deletionPolicy: Retain
 data:
   - secretKey: N8N_LICENSE_ACTIVATION_KEY
     remoteRef:
       conversionStrategy: Default	
       decodingStrategy: None
       metadataPolicy: None
       nullBytePolicy: Ignore
       key: k8s-n8n-license-key