apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
 name: n8n-redis-users-password
 namespace: n8n
spec:
 refreshInterval: 4h0m0s
 secretStoreRef:
   name: azure-store
   kind: ClusterSecretStore
 target:
   name: n8n-redis-users-password
   creationPolicy: Owner
   deletionPolicy: "Retain"
   template:
     type: Opaque
     data:
       password: "{{ .defaultUser }}"
 data:
   - secretKey: defaultUser
     remoteRef:
       conversionStrategy: Default	
       decodingStrategy: None
       metadataPolicy: None
       key: k8s-redis-redis-password
       property: password
       nullBytePolicy: Ignore