apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-postgres
  namespace: n8n
spec:
  refreshInterval: 4h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-postgres-secrets
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "kv/n8n/credentials/postgress"
        metadataPolicy: None
        property: password
        nullBytePolicy: Ignore