apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
 name: n8n-encryption-key
 namespace: n8n
spec:
 refreshInterval: 4h0m0s
 secretStoreRef:
   name: vault-backend
   kind: ClusterSecretStore
 target:
   name: n8n-encryption-key
   creationPolicy: Owner
   deletionPolicy: "Retain"
 data:
   - secretKey: N8N_ENCRYPTION_KEY
     remoteRef:
       conversionStrategy: Default
       decodingStrategy: None
       key: "kv/n8n/credentials/encryption-key"
       metadataPolicy: None
       property: key
       nullBytePolicy: Ignore
   - secretKey: N8N_PROTOCOL
     remoteRef:
       conversionStrategy: Default
       decodingStrategy: None
       key: "kv/n8n/credentials/encryption-key"
       metadataPolicy: None
       property: protocol
       nullBytePolicy: Ignore
   - secretKey: N8N_HOST
     remoteRef:
       conversionStrategy: Default
       decodingStrategy: None
       key: "kv/n8n/credentials/encryption-key"
       metadataPolicy: None
       property: host
       nullBytePolicy: Ignore
   - secretKey: N8N_PORT
     remoteRef:
       conversionStrategy: Default
       decodingStrategy: None
       key: "kv/n8n/credentials/encryption-key"
       metadataPolicy: None
       property: port
       nullBytePolicy: Ignore