apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
 name: n8n-github-secrets
 namespace: n8n
spec:
 refreshInterval: 4h0m0s
 secretStoreRef:
   name: vault-backend
   kind: ClusterSecretStore
 target:
   name: n8n-github-secrets
   creationPolicy: Owner
   deletionPolicy: "Retain"
 data:
   - secretKey: GITHUB_PAT
     remoteRef:
       conversionStrategy: Default
       decodingStrategy: None
       key: "kv/n8n/credentials/github"
       metadataPolicy: None
       property: dev-pat
       nullBytePolicy: Ignore