apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: n8n
  annotations:
    azure.workload.identity/client-id: {{ .Values.schema.esoServiceAccount.clientID }}
    azure.workload.identity/tenant-id: {{ .Values.schema.esoServiceAccount.tenantID }}

