apiVersion: v2
name: n8n
version: 1.0.0
dependencies:
  - name: n8n
    version: 1.9.0
    #repository: "oci://8gears.container-registry.com/library"
    repository: "oci://ghcr.io/n8n-io/n8n-helm-chart"

